#!/usr/bin/env python3
import random
import argparse

parser = argparse.ArgumentParser(description="Generate a random password using the XKCD method")
parser.add_argument("-w", "--words", type=int, default=4,
                   help="reference to WORDS")
parser.add_argument("-n", "--numbers", type=int, default=0,
                   help="include random numbers in the password")
parser.add_argument("-c", "--caps", type=int, default=0,
                   help="capitalize the first letter of the random words")
parser.add_argument("-s", "--symbols", type=int, default=0,
                   help="include random symbols in the password")

args = parser.parse_args()
openWordList = open("words.txt")
wordList = openWordList.read().splitlines()
wordSubsets = random.sample(wordList, args.words)
countCaps = 0
capsLists = []

if (args.caps > 0 and args.caps <= args.words):
   capsSubsets = random.sample(wordSubsets, args.caps)
   wordSubsets = list(set(wordSubsets) - set(capsSubsets))
   while (countCaps < args.caps):
       capsLists.append(capsSubsets[countCaps].title())
       countCaps += 1

   wordSubsets = wordSubsets + capsLists
   random.shuffle(wordSubset)

countNum = 0
numLists = []

if (args.numbers > 0):
   while (args.numbers > countNum):
       tempLists = [str(random.randint(0, 9))]
       countNum += 1
       numLists = numLists + tempLists

   wordSubsets = wordSubsets + numLists
   random.shuffle(wordSubsets)

if (args.symbols > 0):
   symbolList = [";",":",".","*","&","^","%","$","#","@","!","~","(",")","_","|","/"]
   symbolSubset = random.sample(symbolList, args.symbols)

   wordSubsets = wordSubsets + symbolSubset
   random.shuffle(wordSubsets)

password = "".join(wordSubsets)
print(password)
